### ISSUE TITLE
[FEATURE REQUEST] View distance parameter when adding a widget

### ISSUE THREAD

**Issue by iwatkot** [Lucandia/streamlit_stl#2]
Hello!
First of all, I would like to thank you for such a convenient and easy-to-use widget. It really helped me and was very easy to use in my application. Great job!

One small thing I'm missing right now is to set the maximum view distance, when the widget shows an object that is big enough.

Here's an example:

![Kapture 2024-12-04 at 12 15 49](https://github.com/user-attachments/assets/18c28694-a965-4148-921c-e54d7fe9f911)

Current usage:

```python
stl_from_file(
    file_path=stl_preview_path,
    color="#808080",
    material="material",
    auto_rotate=True,
    height="400",
    key=None,
)
```

Desired usage:

```python
stl_from_file(
    file_path=stl_preview_path,
    color="#808080",
    material="material",
    auto_rotate=True,
    height="400",
    key=None,
    view_distance=10000, # ⬅️ This parameter sets the maximum view distance (for example as in Blender).
)
```             

Thank you for your time!

Best regards

**Comment by iwatkot** [comment]
@Lucandia, hello!

Sorry to bother you, but I'm pinging you just in case you've missed this.
I would just like to know whether you would consider implementing this feature or not.

Just let me know.

Thank you so much for your time and efforts in developing this useful widget!

Sincerely

**Comment by Lucandia** [comment]
Hi @iwatkot,
 Sorry for not replying earlier, it's been an intense month.
So, I have some changes incoming for the stl viewer, including improving the docs. I think I can implement the feature you want too, I'll keep you updated.
By chance, is there a model I can easily download to test the viewer?
Thank you so much!
Best,
 Luca

**Comment by iwatkot** [comment]
@Lucandia, thank you so much for replying!

Yes, you can look at how it works here: https://maps4fs.xyz/
Just hit the generate button, don't bother yourself with the settings.

And then, if you download the archive, the STL file will be in the `previews` directory, something like `background_dem.stl`.

If you don't want to bother yourself with generation, here's the file: https://drive.google.com/file/d/1wEU6S76ZWXxjG6nIhxWhX2qV5llZiodN/view?usp=sharing

I just thought it might be useful for you to see the actual use case in the browser.

Sincerely

**Comment by Lucandia** [comment]
Hi @iwatkot,
 I just implemented some of parameters for camera control and added a max_view_distance parameter.
I already pushed the code and updated the version on PyPI, so if you do `pip install streamlit-stl --upgrade` you should be able to use it right away!
Let me know if it works properly for you!
Best,
 Luca

**Comment by iwatkot** [comment]
@Lucandia, thank you for the fast upgrade!

View distance works as a charm. But with new camera angles, I can't find the way the object rotates as it was before.

Earlier, the axis of rotation was in the center of the object (which represents the terrain). Now, it rotates as a coin or something. Meaning the axis of rotation changed.
I've tried like 10 different combinations of camera angles but still can't figure it out.

How it looks now.
![image](https://github.com/user-attachments/assets/ce6bb6d9-0a39-457a-9cb9-4968b6132fe5)

How it looks on the earlier version.
![image](https://github.com/user-attachments/assets/0c096e47-b8cd-40b2-9bc9-1f037c60ecc6)


What am I doing wrong? Maybe you can suggest camera angles for my case?

Thank you for your help!

**Comment by iwatkot** [comment]
@Lucandia, for better understanding.

Old version:

![Kapture 2024-12-27 at 19 09 46](https://github.com/user-attachments/assets/234026da-c686-47f3-b7e9-068e8316d66a)

New version:

![Kapture 2024-12-27 at 19 11 18](https://github.com/user-attachments/assets/86fbcf53-0f72-4b40-9c33-6e4bb911c5c1)


I also noticed the changes in the object's appearance. It looks like in the old version, it was something brighter. Can I change this behavior?

Thank you once more

**Comment by Lucandia** [comment]
Okay, I hope I fixed the rotation, I had to change the reference system. I'll have a look into the brightness tomorrow!
Cheers,
 Luca

**Comment by iwatkot** [comment]
@Lucandia, thanks! 🙏

Works perfectly now.

**Comment by Lucandia** [comment]
I put the 3D shading back to Phong with high shininess, so the brightness should be like the first version.
I hope this is fine. I want to keep only these three material options since adding more materials would increase the complexity a lot, and I want to keep it simple.
Let me know if it works for you!
Best,
 Luca

**Comment by iwatkot** [comment]
@Lucandia, thank you for the update

But to be honest, I can't see any difference with 0.0.4 in the meaning of the visuals. It's still gray and not as cool as in 0.0.2. :D

![image](https://github.com/user-attachments/assets/d910f528-e407-46c4-b82c-297bc1d45eb6)


```python
stl_from_file(
    file_path=stl_preview_path,
    color="#808080",
    material="material",
    auto_rotate=True,
    height="400",
    key=None,
    max_view_distance=10000,
)
```

But actually, I can live without it, so you may not bother yourself with it.
Feel free to close the issue at any time, even if you don't want to do anything about it. You have already done much!

Thank you
Best Regards

**Comment by Lucandia** [comment]
Ops, it wasn't what I expected.
Sorry, I'm new to JS and Three.js. I was curious, so I looked into it and I had to change the reference axis for the lights since I did for the camera! 
It should look the same as v0.0.2 now.
Thank you very much and enjoy!
Have a nice day,
 Luca

**Comment by iwatkot** [comment]
@Lucandia, looks awesome!

Thank you so much!
FYI: Added you in the Special thanks section: https://github.com/iwatkot/maps4fs?tab=readme-ov-file#special-thanks
